# Generated by Django 5.0.4 on 2024-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Élève'), ('professeur', 'Professeur')], default='eleve', max_length=20),
        ),
    ]
