# Generated by Django 4.2.10 on 2024-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_rating_roomrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
