# Generated by Django 5.0.4 on 2024-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_payees'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='room_files/'),
        ),
    ]
